# Monitors everything on the antique box you refuse to retire. Alerts you before the HDDs start auditioning for a maraca band.
name: ctrl-alt-decrepit

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor    
    command:
      - "--disable_metrics=perf_event"
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /volume1/@docker:/var/lib/docker:ro
    expose:
      - 8080
  
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    ports:
      - 8120:8120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100

  scrutiny-collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    container_name: scrutiny-collector
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - '/run/udev:/run/udev:ro'
      - /volume1/docker/scrutiny-collector:/opt/scrutiny/config
    environment:
      - SCRUTINY_COLLECTOR_API_ENDPOINT=${SCRUTINY_COLLECTOR_API_ENDPOINT}
      - SCRUTINY_COLLECTOR_HOST_ID=prime-ds
      - SCRUTINY_COLLECTOR_RUN_STARTUP=true
    restart: unless-stopped
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sde"
      - "/dev/sdf"
