# Monitors everything on the antique box you refuse to retire. Alerts you before the HDDs start auditioning for a maraca band.
name: ctrl-alt-decrepit

services:
  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    ports:
      - 8120:8120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo

  scrutiny-collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    container_name: scrutiny-collector
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - '/run/udev:/run/udev:ro'
      - /volume1/docker/scrutiny-collector:/opt/scrutiny/config
    environment:
      - SCRUTINY_COLLECTOR_API_ENDPOINT=${SCRUTINY_COLLECTOR_API_ENDPOINT}
      - SCRUTINY_COLLECTOR_HOST_ID=prime-ds
      - SCRUTINY_COLLECTOR_RUN_STARTUP=true
    restart: unless-stopped
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sde"
      - "/dev/sdf"
