# A stack full of services that either don’t talk to each other or talk way too much. Guaranteed to consume CPU doing nothing useful.
name: absolute-nonsense

services:
  
  f1timing:
    image: ghcr.io/adn8naiagent/f1replaytiming:latest
    container_name: f1timing
    env_file: ./env/f1timing.env
    mem_limit: 768m    
    cpus: 0.88
    networks:
      - web
    restart: unless-stopped
    volumes:
      #- f1replay-cache:/data/fastf1-cache
      - f1replay-data:/data
    labels:
      - flame.type=application
      - flame.category=Fun and games
      - flame.name=F1 Replay Timing
      - flame.url=https://f1timing.${DOMAIN}
      - flame.icon=flag-checkered
      - traefik.enable=true
      - traefik.http.routers.f1timing.rule=Host(`f1timing.${DOMAIN}`)
      - traefik.http.routers.f1timing.entrypoints=websecure
      - traefik.http.routers.f1timing.tls.certresolver=letsencrypt
      - traefik.http.routers.f1timing.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.f1timing.middlewares=authentik@file,umami@file
      - traefik.http.services.f1timing.loadbalancer.server.port=3000
    

  hypermind:    
    image: 'ghcr.io/lklynet/hypermind:1.0.0'
    container_name: hypermind
    environment:
      - ENABLE_THEMES=true
      - ENABLE_MAP=true
      - ENABLE_CHAT=true
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      web:
    mem_limit: 330m    
    cpus: 0.33
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Fun and games
      - flame.name=Hypermind
      - flame.url=https://hypermind.${DOMAIN}
      - flame.icon=brain
      - traefik.enable=true
      - traefik.http.routers.hypermind.rule=Host(`hypermind.${DOMAIN}`)
      - traefik.http.routers.hypermind.entrypoints=websecure
      - traefik.http.routers.hypermind.tls.certresolver=letsencrypt
      - traefik.http.routers.hypermind.priority=${TRAEFIK_PRIORITY}
      - traefik.http.services.hypermind.loadbalancer.server.port=3000

networks:
  web:
    external: true

volumes:
  f1replay-cache:
    external: true
  f1replay-data:
    external: true 