# A safe space for databases with commitment issues. Whether it’s time‑series drama, relational overthinking, document‑storage chaos, or PostgreSQL’s “I’m smarter than everyone else” attitude — this stack collects, stores, and protects every bit you throw at it. Perfect for when you absolutely, definitely, totally need that metric from 8 months ago at 03:12… someday.
name: databases

services:
  adminneo:
    image: adminneoorg/adminneo:latest
    container_name: adminneo
    networks:
      backend:
      web:
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Databases
      - flame.name=AdminNeo
      - flame.url=https://dba.${DOMAIN}
      - flame.icon=database-cog-outline
      - traefik.enable=true
      - traefik.http.routers.adminneo.rule=Host(`dba.${DOMAIN}`)
      - traefik.http.routers.adminneo.entrypoints=websecure
      - traefik.http.routers.adminneo.tls.certresolver=letsencrypt
      - traefik.http.routers.adminneo.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.adminneo.middlewares=authentik@file
      - traefik.http.services.adminneo.loadbalancer.server.port=8080

  influxdb:
    image: docker.io/influxdb:latest
    container_name: influxdb
    networks:
      backend:
      web:      
    volumes:
      - type: volume
        source: influxdb
        target: /etc/influxdb2
        volume:
          subpath: config
      - type: volume
        source: influxdb
        target: /var/lib/influxdb2
        volume:
          subpath: data
    ports:
      - 8086:8086
    env_file: ../../../global.env    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 11s
      timeout: 11s
      retries: 22
    labels:
      - flame.type=application
      - flame.category=Databases
      - flame.name=InfluxDB
      - flame.url=https://influxdb.${DOMAIN}
      - flame.icon=database-cog-outline
      - traefik.enable=true
      - traefik.http.routers.influxdb.rule=Host(`influxdb.${DOMAIN}`)
      - traefik.http.routers.influxdb.entrypoints=websecure
      - traefik.http.routers.influxdb.tls.certresolver=letsencrypt
      - traefik.http.routers.influxdb.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.influxdb.middlewares=authentik@file
      - traefik.http.services.influxdb.loadbalancer.server.port=8086
      
  mariadb:
    image: docker.io/mariadb:latest
    container_name: mariadb
    networks:
      backend:
    env_file: ./env/mariadb.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  postgresql-authentik:
    image: docker.io/library/postgres:16-alpine
    container_name: postgresql-authentik
    env_file: ./env/postgresql-authentik.env
    user: ${PUID}:${PGID}
    networks:
      backend:
    volumes:
    - postgresql-authentik:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${AUTHENTIK_PG_DB} -U $${AUTHENTIK_PG_USER}
      timeout: 5s

  postgresql-immich:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: postgresql-immich
    env_file: ./env/postgresql-immich.env
    volumes:
      - postgresql-immich:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${IMMICH_PG_DB} -U $${IMMICH_PG_USER}
      timeout: 5s

  postgresql-scanopy:
    image: postgres:17-alpine
    container_name: postgresql-scanopy
    env_file: ./env/postgresql-scanopy.env
    volumes:
      - postgresql-scanopy:/var/lib/postgresql/data
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${SCANOPY_PG_DB} -U $${SCANOPY_PG_USER}
      timeout: 5s
    restart: unless-stopped
    networks:
      - backend

#  mongodb:
#    image: mongo
#    container_name: mongodb
#  postgresql:
#    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
#    container_name: postgresql  

networks:
  backend:
    external: true
  web:
    external: true

volumes:
  influxdb:
    external: true
  mariadb:
    external: true
  mongodb:
    external: true
  postgresql-authentik:
    external: true
  postgresql-immich:
    external: true
  postgresql-scanopy:
    external: true