# A safe space for databases with commitment issues. Whether it’s time‑series drama, relational overthinking, document‑storage chaos, or PostgreSQL’s “I’m smarter than everyone else” attitude — this stack collects, stores, and protects every bit you throw at it. Perfect for when you absolutely, definitely, totally need that metric from 8 months ago at 03:12… someday.
name: databases

services:
  influxdb:
    image: docker.io/influxdb:latest
    container_name: influxdb
    networks:
      backend:
      web:      
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2
    ports:
      - 8086:8086
    env_file:
      - ../../../global.env    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 11s
      timeout: 11s
      retries: 22
      
  mariadb:
    image: docker.io/mariadb:latest
    container_name: mariadb
    networks:
      backend:
    env_file:
      - ./env/mariadb.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  postgresql-authentik:
    image: docker.io/library/postgres:16-alpine
    container_name: postgresql-authentik
    env_file:
      - ./env/postgresql-authentik.env
    user: ${PUID}:${PGID}
    networks:
      backend:
    volumes:
    - postgresql-authentik:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${AUTHENTIK_PG_DB} -U $${AUTHENTIK_PG_USER}
      timeout: 5s

#  mongodb:
#    image: mongo
#    container_name: mongodb
#  postgresql:
#    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
#    container_name: postgresql  

networks:
  backend:
    external: true
  web:
    external: true

volumes:
  postgresql-authentik:
    external: true
  influxdb-config:
    external: true
  influxdb-data:
    external: true
  mariadb:
    external: true
  mongodb:
    external: true
  postgresql:  
    external: true