# A safe space for databases with commitment issues. Whether it’s time‑series drama, relational overthinking, document‑storage chaos, or PostgreSQL’s “I’m smarter than everyone else” attitude — this stack collects, stores, and protects every bit you throw at it. Perfect for when you absolutely, definitely, totally need that metric from 8 months ago at 03:12… someday.
name: databases

services:
  influxdb:
    image: docker.io/influxdb:latest
    container_name: influxdb
    networks:
      backend:
      web:      
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 11s
      timeout: 11s
      retries: 22
#  mariadb:
#    image: docker.io/mariadb:latest
#    container_name: mariadb
#  mongodb:
#    image: mongo
#    container_name: mongodb
#  postgresql:
#    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
#    container_name: postgresql  

networks:
  backend:
    external: true
  web:
    external: true

volumes:
  influxdb-config:
    external: true
  influxdb-data:
    external: true
  mariadb:
    external: true
  mongodb:
    external: true
  postgresql:  
    external: true