# Whispers file changes between providers and hopes nobody misses the memo.
name: cloud-gossip

services:
  
  dropbox:
    image: rbonghi/dropbox:latest
    container_name: dropbox
    command: ["--fromDropbox", "-i", "660"]
    user: ${PUID}:${PGID}
    environment:
      - PYTHONUNBUFFERED=1
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
      - DROPBOX_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN}
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - dropbox:/dropbox

  icloud:
    image: mandarons/icloud-drive
    container_name: icloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - ENV_CONFIG_FILE_PATH=/config/config.yaml
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - icloud:/icloud
      - icloud-config:/config
      - icloud-keyring:/home/abc/.local

    #TODO:
    # OneDrive: 
    #   - https://hub.docker.com/r/driveone/onedrive
    #   - https://forums.unraid.net/topic/132486-guide-set-up-the-onedrive-client-for-linux-abraunegg-as-docker-container/ 
    # Google Drive:
    #   - https://github.com/richardregeer/docker-google-drive-sync

volumes:
  dropbox:
    external: true
  icloud:
    external: true
  icloud-config:
    external: true
  icloud-keyring:
    external: true