# Monitors everything and escalates threats immediately… even if it’s just a slightly warm HDD.
name: ctrl-alt-defcon

services:
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    privileged: true        
    command:
      - "--disable_metrics=perf_event,disk,diskIO"
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - monitoring

  godns:
    container_name: godns
    image: timothyye/godns:latest
    networks:
      - web
    environment:
      - CONFIG=/config/config.json
    restart: unless-stopped
    volumes:
      - godns:/config/
    labels:
      - flame.type=application
      - flame.category=CTRL ALT DEFCON
      - flame.name=GoDNS
      - flame.url=https://godns.${DOMAIN}
      - flame.icon=dns-outline
      - traefik.enable=true
      - traefik.http.routers.godns.rule=Host(`godns.${DOMAIN}`)
      - traefik.http.routers.godns.entrypoints=websecure
      - traefik.http.routers.godns.tls.certresolver=letsencrypt
      - traefik.http.routers.godns.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.godns.middlewares=crowdsec@file,geoblock@file
      - traefik.http.services.godns.loadbalancer.server.port=9099

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    restart: unless-stopped
    expose:
      - 9104 
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${PROMETHEUS_MARIADB_PASSWORD}
    command:
      - "--mysqld.address=mariadb.backend:3306"
      - "--mysqld.username=${PROMETHEUS_MARIADB_USER}"
    networks:
      - backend
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--storage.tsdb.retention.time=30d"
    networks:
      - backend
      - monitoring
      - web
    volumes:
      - prometheus:/prometheus
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=CTRL ALT DEFCON
      - flame.name=Prometheus
      - flame.url=https://prometheus.${DOMAIN}
      - flame.icon=chart-line
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.routers.prometheus.tls.certresolver=letsencrypt
      - traefik.http.routers.prometheus.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.prometheus.middlewares=crowdsec@file,geoblock@file,authentik@file
      - traefik.http.services.prometheus.loadbalancer.server.port=9090

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    restart: unless-stopped
    expose:
      - 9121
    environment:
      - REDIS_ADDR="redis://redis.cache:6379"
    networks:
      - cache
      - monitoring

  scrutiny-collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    container_name: scrutiny-collector
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - '/run/udev:/run/udev:ro'
      - scrutiny:/opt/scrutiny/config      
    networks:
      - monitoring
    environment:
      COLLECTOR_API_ENDPOINT: 'http://scrutiny-web.scrutiny:8080'
      COLLECTOR_HOST_ID: 'prime'
      COLLECTOR_RUN_STARTUP: true
    restart: unless-stopped    
    devices:
      - "/dev/nvme0"
  
  scrutiny-exporter:
    image: jianyun8023/scrutiny-exporter:latest
    container_name: scrutiny-exporter
    restart: unless-stopped
    environment:
      - SCRUTINY_API_URL=http://scrutiny-web.monitoring:8080
      - EXPORTER_PORT=9900
      - CACHE_DURATION=60
    networks:
      - monitoring
    expose:
      - 9900

  scrutiny-web:
    image: 'ghcr.io/analogj/scrutiny:master-web'
    container_name: scrutiny-web
    volumes:
      - scrutiny:/opt/scrutiny/config
    networks:
      - backend
      - monitoring
      - web
    restart: unless-stopped    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    labels:
      - flame.type=application
      - flame.category=CTRL ALT DEFCON
      - flame.name=Scrutiny
      - flame.url=https://scrutiny.${DOMAIN}
      - flame.icon=harddisk
      - traefik.enable=true
      - traefik.http.routers.scrutiny.rule=Host(`scrutiny.${DOMAIN}`)
      - traefik.http.routers.scrutiny.entrypoints=websecure
      - traefik.http.routers.scrutiny.tls.certresolver=letsencrypt
      - traefik.http.routers.scrutiny.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.scrutiny.middlewares=crowdsec@file,geoblock@file,authentik@file
      - traefik.http.services.scrutiny.loadbalancer.server.port=8080

  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    networks:
      - backend
      - web
    env_file:
      - ../../../global.env
      - ./env/speedtest-tracker.env
    restart: unless-stopped
    ports:
      - 8033:80
    volumes:
      - speedtest-tracker:/config
    labels:
      - flame.type=application
      - flame.category=CTRL ALT DEFCON
      - flame.name=Speedtest Tracker
      - flame.url=https://speedtest.${DOMAIN}
      - flame.icon=speedometer
      - traefik.enable=true
      - traefik.http.routers.speedtest-tracker.rule=Host(`speedtest.${DOMAIN}`)
      - traefik.http.routers.speedtest-tracker.entrypoints=websecure
      - traefik.http.routers.speedtest-tracker.tls.certresolver=letsencrypt
      - traefik.http.routers.speedtest-tracker.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.speedtest-tracker.middlewares=crowdsec@file,geoblock@file
      - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80
  
  zfs-exporter:
    image: matusnovak/prometheus-zfs:latest
    container_name: zfs-exporter
    restart: unless-stopped
    privileged: true
    expose:
      - 9901
    networks:
      - monitoring

networks:
  backend:
    external: true
  cache:
    external: true
  monitoring:
    external: true
  web:
    external: true

volumes:
  godns:
    external: true
  prometheus:
    external: true
  scrutiny:
    external: true
  speedtest-tracker:
    external: true