# A distributed system designed to solve critical problems like “why is the hallway light still on?”
# Overengineered? Absolutely. Regret? Minimal.
name: home-automation

services:
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      macvlan:
        ipv4_address: ${MACVLAN_STATIC_IP_ESPHOME}
      web:
    volumes:
      - esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esphome.rule=Host(`esphome.${DOMAIN}`)"
      - "traefik.http.routers.esphome.entrypoints=websecure"
      - "traefik.http.routers.esphome.tls.certresolver=letsencrypt"
      - "traefik.http.routers.esphome.middlewares=authentik"
      - "traefik.http.services.esphome.loadbalancer.server.port=6052"

  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.17.0-rc3
    container_name: frigate
    environment:
      - TZ=${TZ}
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}
    #  - GIDLIST=44,993
      - LIBVA_DRIVER_NAME=iHD
    shm_size: 512mb
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128 
    device_cgroup_rules:
      - 'c 226:* rmw'    
    #group_add:
    #  - 'video'  # "44"
    #  - 'render' # "993"
    ports:
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    networks:
      - backend
      - web
    volumes:
      - frigate:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/prime-ds/media/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    #privileged: true
    stop_grace_period: 22s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate-rc.rule=Host(`frigate-rc.${DOMAIN}`)"
      - "traefik.http.routers.frigate-rc.entrypoints=websecure"
      - "traefik.http.routers.frigate-rc.tls.certresolver=letsencrypt"
      - "traefik.http.services.frigate-rc.loadbalancer.server.port=8971"

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    devices:
      - /dev/bus/usb:/dev/bus/usb      
    networks:
      backend:
      macvlan:
        ipv4_address: ${MACVLAN_STATIC_IP_HOME_ASSISTANT}
      web:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.rule=Host(`has.${DOMAIN}`)"
      - "traefik.http.routers.home-assistant.entrypoints=websecure"
      - "traefik.http.routers.home-assistant.tls.certresolver=letsencrypt"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    networks:
      - backend
    volumes:
      - mosquitto:/mosquitto
    restart: unless-stopped

  music-assistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant
    environment:
      - TZ=${TZ}
    networks:
      backend:
      macvlan:
        ipv4_address: ${MACVLAN_STATIC_IP_MUSIC_ASSISTANT}
    volumes:
      - music-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    networks:
      - backend
      - web
    volumes:
      - node-red:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-red.rule=Host(`nodered.${DOMAIN}`)"
      - "traefik.http.routers.node-red.entrypoints=websecure"
      - "traefik.http.routers.node-red.tls.certresolver=letsencrypt"
      - "traefik.http.routers.node-red.middlewares=authentik"
      - "traefik.http.services.node-red.loadbalancer.server.port=1880"

networks:
  backend:
    external: true
  macvlan:
    external: true
  web:
    external: true

volumes:
  esphome:
    external: true
  frigate:
    external: true
  home-assistant:
    external: true
  mosquitto:
    external: true
  music-assistant:
    external: true
  node-red:
    external: true