# A distributed system designed to solve critical problems like “why is the hallway light still on?”
# Overengineered? Absolutely. Regret? Minimal.
name: home-automation

services:
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      macvlan:
        ipv4_address: ${MACVLAN_STATIC_IP_ESPHOME}
      web:
    volumes:
      - esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Home Automation
      - flame.name=ESPHome
      - flame.url=https://esphome.${DOMAIN}
      - flame.icon=memory
      - flame.order=3
      - traefik.enable=true
      - traefik.http.routers.esphome.rule=Host(`esphome.${DOMAIN}`)
      - traefik.http.routers.esphome.entrypoints=websecure
      - traefik.http.routers.esphome.tls.certresolver=letsencrypt
      - traefik.http.routers.esphome.middlewares=oidc-auth@file
      - traefik.http.services.esphome.loadbalancer.server.port=6052

  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.18.0-beta3
    container_name: frigate
    environment:
      - TZ=${TZ}
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}
      - GIDLIST=44,993
      - LIBVA_DRIVER_NAME=iHD
    shm_size: 512mb
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    group_add:
      - '44'   # 'video'
      - '993'  # 'render'
    ports:
      - 1984:1984
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    cap_add:
      - CAP_PERFMON
    networks:
      - backend
      - web
    env_file: ./env/frigate.env
    volumes:
      - frigate:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/prime-ds/media/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    stop_grace_period: 22s
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Home Automation
      - flame.name=Frigate
      - flame.url=https://frigate.${DOMAIN}
      - flame.icon=cctv
      - flame.order=2
      - traefik.enable=true
      - traefik.http.routers.frigate-rc.rule=Host(`frigate.${DOMAIN}`)
      - traefik.http.routers.frigate-rc.entrypoints=websecure
      - traefik.http.routers.frigate-rc.tls.certresolver=letsencrypt
      #- traefik.http.routers.frigate-rc.middlewares=crowdsec@file,geoblock@file
      - traefik.http.services.frigate-rc.loadbalancer.server.port=8971

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    env_file: ../../../global.env
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0     
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Home Automation
      - flame.name=Home Assistant
      - flame.url=https://has.${DOMAIN}
      - flame.icon=home-outline
      - flame.order=1
      - traefik.enable=true
      - traefik.http.routers.home-assistant.rule=Host(`has.${DOMAIN}`)
      - traefik.http.routers.home-assistant.entrypoints=websecure
      - traefik.http.routers.home-assistant.tls.certresolver=letsencrypt
      - traefik.http.services.home-assistant.loadbalancer.server.url=http://${GLOBAL_SERVER_URL}:8123

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    environment:
      - TZ=${TZ}
    networks:
      - backend
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto:/mosquitto
    restart: unless-stopped

  music-assistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant
    env_file: ../../../global.env    
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    network_mode: host
    volumes:
      - music-assistant:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    networks:
      - backend
      - web
    volumes:
      - node-red:/data
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Home Automation
      - flame.name=Node-RED
      - flame.url=https://nodered.${DOMAIN}
      - flame.icon=state-machine
      - flame.order=4
      - traefik.enable=true
      - traefik.http.routers.node-red.rule=Host(`nodered.${DOMAIN}`)
      - traefik.http.routers.node-red.entrypoints=websecure
      - traefik.http.routers.node-red.tls.certresolver=letsencrypt
      - traefik.http.services.node-red.loadbalancer.server.port=1880

networks:
  backend:
    external: true
  macvlan:
    external: true
  web:
    external: true

volumes:
  esphome:
    external: true
  frigate:
    external: true
  home-assistant:
    external: true
  mosquitto:
    external: true
  music-assistant:
    external: true
  node-red:
    external: true