name: komodo

services:
  komodo-mongodb:
    image: mongo
    container_name: komodo-mongodb
    networks:
      - backend
    labels:
      - komodo.skip=true
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - komodo-mongodb-config:/data/configdb
      - komodo-mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
  
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:2
    container_name: komodo-core
    init: true
    restart: unless-stopped
    networks:
      - backend
      - web
    env_file: .env
    environment:
      - KOMODO_DATABASE_ADDRESS=komodo-mongodb:27017
      - KOMODO_DATABASE_USERNAME=${KOMODO_DB_USERNAME}
      - KOMODO_DATABASE_PASSWORD=${KOMODO_DB_PASSWORD}
      - KOMODO_OIDC_ENABLED=true
      - KOMODO_OIDC_PROVIDER=${KOMODO_OIDC_PROVIDER}
      - KOMODO_OIDC_CLIENT_ID=${KOMODO_OIDC_CLIENT_ID}
      - KOMODO_OIDC_CLIENT_SECRET=${KOMODO_OIDC_CLIENT_SECRET}
    volumes:
      - komodo-core-backups:/backups
      - komodo-keys:/config/keys
    labels:
      - komodo.skip=true
      - traefik.enable=true
      - traefik.http.routers.komodo.rule=Host(`komodo.${DOMAIN}`)
      - traefik.http.routers.komodo.entrypoints=websecure
      - traefik.http.routers.komodo.tls.certresolver=letsencrypt
      - traefik.http.routers.komodo.priority=${TRAEFIK_PRIORITY}
      - traefik.http.services.komodo.loadbalancer.server.port=9120

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    container_name: komodo-periphery
    init: true
    env_file: .env
    networks:
      - backend    
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
      - komodo-keys:/config/keys
    labels:
      - komodo.skip=true

networks:
  web:
    external: true
  backend:
    external: true

volumes:
  komodo-core-backups:
    external: true
  komodo-keys:
    external: true
  komodo-mongodb-config:
    external: true
  komodo-mongodb-data:
    external: true
