# Where all your movies and shows disappear into the deep… and instantly resurface
# in Plex like nothing ever happened.
name: new-providence-island

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - bazarr:/config
      - ${VOLUME_PATH_MOVIES_HOST}:${VOLUME_PATH_MOVIES_CONTAINER}
      - ${VOLUME_PATH_TV_HOST}:${VOLUME_PATH_TV_CONTAINER}
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Captain’s Quarters
      - flame.name=Bazarr
      - flame.url=https://bazarr.${DOMAIN}
      - flame.icon=subtitles-outline
      - traefik.enable=true
      - traefik.http.routers.bazarr-api.rule=Host(`bazarr.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.bazarr-api.entrypoints=websecure
      - traefik.http.routers.bazarr-api.priority=100
      - traefik.http.routers.bazarr-api.tls=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.tls.certresolver=letsencrypt
      - traefik.http.routers.bazarr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.bazarr.middlewares=authentik@file
      - traefik.http.services.bazarr.loadbalancer.server.port=6767

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - decluttarr:/app/config
      - ${VOLUME_PATH_DOWNLOADS_HOST}:${VOLUME_PATH_DOWNLOADS_CONTAINER}
      - ${VOLUME_PATH_MOVIES_HOST}:${VOLUME_PATH_MOVIES_CONTAINER}
      - ${VOLUME_PATH_MUSIC_HOST}:${VOLUME_PATH_MUSIC_CONTAINER}
      - ${VOLUME_PATH_TV_HOST}:${VOLUME_PATH_TV_CONTAINER}
    restart: unless-stopped

  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    networks:
      - dirty-water
    env_file:
      - ../../../global.env
    volumes:
      - kometa:/config
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - lidarr:/config
      - ${VOLUME_PATH_MUSIC_HOST}:${VOLUME_PATH_MUSIC_CONTAINER}
      - ${VOLUME_PATH_DOWNLOADS_HOST}:${VOLUME_PATH_DOWNLOADS_CONTAINER}
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Captain’s Quarters
      - flame.name=Lidarr
      - flame.url=https://lidarr.${DOMAIN}
      - flame.icon=music-clef-treble
      - traefik.enable=true
      - traefik.http.routers.lidarr-api.rule=Host(`lidarr.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.lidarr-api.entrypoints=websecure
      - traefik.http.routers.lidarr-api.priority=100
      - traefik.http.routers.lidarr-api.tls=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)
      - traefik.http.routers.lidarr.entrypoints=websecure
      - traefik.http.routers.lidarr.tls.certresolver=letsencrypt
      - traefik.http.routers.lidarr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.services.lidarr.loadbalancer.server.port=8686

  plex:
    image: 'lscr.io/linuxserver/plex:latest'
    container_name: plex
    networks:
      dirty-water:
      macvlan:
        ipv4_address: ${MACVLAN_STATIC_IP_PLEX}
      web:
    env_file:
      - ../../../global.env
      - ./env/plex.env
    devices:
      - '/dev/dri:/dev/dri'    
    device_cgroup_rules:
      - 'c 226:* rmw'    
    group_add:
      - 'video'  # "44"
      - 'render' # "993"
    volumes:
      - plex:/config
      - /usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri:ro
      - ${VOLUME_PATH_MOVIES_HOST}:${VOLUME_PATH_MOVIES_CONTAINER}
      - ${VOLUME_PATH_MUSIC_HOST}:${VOLUME_PATH_MUSIC_CONTAINER}
      - ${VOLUME_PATH_TV_HOST}:${VOLUME_PATH_TV_CONTAINER}
    restart: unless-stopped 
    labels:
      - flame.type=application
      - flame.category=Pirate’s Tavern
      - flame.name=Plex
      - flame.url=https://plex.${DOMAIN}
      - flame.icon=plex
      - flame.order=1
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=letsencrypt
      - traefik.http.routers.plex.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.plex.middlewares=authentik@file
      - traefik.http.services.plex.loadbalancer.server.port=32400

  plex-auto-languages:
    image: remirigal/plex-auto-languages:latest
    container_name: plex-auto-languages
    environment:
      - TZ=${TZ}
    networks:
      dirty-water:
    volumes:      
      - plexautolanguages:/config
    restart: unless-stopped

  posterizarr:
    image: ghcr.io/fscorrupt/posterizarr:latest
    container_name: posterizarr
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    user: ${PUID}:${PGID}
    networks:
      - web
    volumes:
      - posterizarr:/config:rw
    labels:
      - flame.type=application
      - flame.category=Captain’s Quarters
      - flame.name=Posterizarr
      - flame.url=https://posterizarr.${DOMAIN}
      - flame.icon=image-search-outline
      - traefik.enable=true
      - traefik.http.routers.posterizarr.rule=Host(`posterizarr.${DOMAIN}`)
      - traefik.http.routers.posterizarr.entrypoints=websecure
      - traefik.http.routers.posterizarr.tls.certresolver=letsencrypt
      - traefik.http.routers.posterizarr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.posterizarr.middlewares=authentik@file
      - traefik.http.services.posterizarr.loadbalancer.server.port=8000

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    networks:
      - web
    volumes:
      - profilarr:/config
    env_file: ../../../global.env
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Captain’s Quarters
      - flame.name=Profilarr
      - flame.url=https://profilarr.${DOMAIN}
      - flame.icon=search-web
      - traefik.enable=true
      - traefik.http.routers.profilarr.rule=Host(`profilarr.${DOMAIN}`)
      - traefik.http.routers.profilarr.entrypoints=websecure
      - traefik.http.routers.profilarr.tls.certresolver=letsencrypt
      - traefik.http.routers.profilarr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.profilarr.middlewares=authentik@file
      - traefik.http.services.profilarr.loadbalancer.server.port=6868

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - prowlarr:/config
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Captain’s Quarters
      - flame.name=Prowlarr
      - flame.url=https://prowlarr.${DOMAIN}
      - flame.icon=search-web
      - traefik.enable=true
      - traefik.http.routers.prowlarr-api.rule=Host(`prowlarr.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.prowlarr-api.entrypoints=websecure
      - traefik.http.routers.prowlarr-api.priority=100
      - traefik.http.routers.prowlarr-api.tls=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.tls.certresolver=letsencrypt
      - traefik.http.routers.prowlarr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.prowlarr.middlewares=authentik@file
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - radarr:/config
      - ${VOLUME_PATH_MOVIES_HOST}:${VOLUME_PATH_MOVIES_CONTAINER}
      - ${VOLUME_PATH_DOWNLOADS_HOST}:${VOLUME_PATH_DOWNLOADS_CONTAINER}
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Captain’s Quarters
      - flame.name=Radarr
      - flame.url=https://radarr.${DOMAIN}
      - flame.icon=movie-search-outline
      - traefik.enable=true
      - traefik.http.routers.radarr-api.rule=Host(`radarr.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.radarr-api.entrypoints=websecure
      - traefik.http.routers.radarr-api.priority=100
      - traefik.http.routers.radarr-api.tls=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls.certresolver=letsencrypt
      - traefik.http.routers.radarr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.radarr.middlewares=authentik@file
      - traefik.http.services.radarr.loadbalancer.server.port=7878
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - sabnzbd:/config
      - ${VOLUME_PATH_DOWNLOADS_HOST}:${VOLUME_PATH_DOWNLOADS_CONTAINER}
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Pirate’s Tavern
      - flame.order=4
      - flame.name=SABnzbd
      - flame.url=https://sabnzbd.${DOMAIN}
      - flame.icon=cloud-download-outline
      - traefik.enable=true
      - traefik.http.routers.sabnzbd-api.rule=Host(`sabnzbd.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.sabnzbd-api.entrypoints=websecure
      - traefik.http.routers.sabnzbd-api.priority=100
      - traefik.http.routers.sabnzbd-api.tls=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.http.routers.sabnzbd.entrypoints=websecure
      - traefik.http.routers.sabnzbd.tls.certresolver=letsencrypt
      - traefik.http.routers.sabnzbd.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.sabnzbd.middlewares=authentik@file
      - traefik.http.services.sabnzbd.loadbalancer.server.port=3389
  
  seerr:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    networks:
      - web
    restart: unless-stopped
    volumes:
      - seerr:/app/config
    env_file: ../../../global.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    labels:
      - flame.type=application
      - flame.category=Pirate’s Tavern
      - flame.order=2
      - flame.name=Seerr
      - flame.url=https://seerr.${DOMAIN}
      - flame.icon=movie-search-outline
      - traefik.enable=true
      - traefik.http.routers.seerr-api.rule=Host(`seerr.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.seerr-api.entrypoints=websecure
      - traefik.http.routers.seerr-api.priority=100
      - traefik.http.routers.seerr-api.tls=true
      - traefik.http.routers.seerr.rule=Host(`seerr.${DOMAIN}`)
      - traefik.http.routers.seerr.entrypoints=websecure
      - traefik.http.routers.seerr.tls.certresolver=letsencrypt
      - traefik.http.routers.seerr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.seerr.middlewares=authentik@file
      - traefik.http.services.seerr.loadbalancer.server.port=5055

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - sonarr:/config
      - ${VOLUME_PATH_DOWNLOADS_HOST}:${VOLUME_PATH_DOWNLOADS_CONTAINER}
      - ${VOLUME_PATH_TV_HOST}:${VOLUME_PATH_TV_CONTAINER}
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Captain’s Quarters
      - flame.name=Sonarr
      - flame.url=https://sonarr.${DOMAIN}
      - flame.icon=movie-search-outline
      - traefik.enable=true
      - traefik.http.routers.sonarr-api.rule=Host(`sonarr.${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.sonarr-api.entrypoints=websecure
      - traefik.http.routers.sonarr-api.priority=100
      - traefik.http.routers.sonarr-api.tls=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls.certresolver=letsencrypt
      - traefik.http.routers.sonarr.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.sonarr.middlewares=authentik@file
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    networks:
      - web
    env_file: ../../../global.env
    volumes:
      - tautulli:/config
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.category=Pirate’s Tavern
      - flame.order=3
      - flame.name=Tautulli
      - flame.url=https://tautulli.${DOMAIN}
      - flame.icon=eye-check-outline
      - traefik.enable=true
      - traefik.http.routers.tautulli-bypass.rule=Host(`tautulli.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/image`))
      - traefik.http.routers.tautulli-bypass.entrypoints=websecure
      - traefik.http.routers.tautulli-bypass.priority=100
      - traefik.http.routers.tautulli-bypass.tls=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN}`)
      - traefik.http.routers.tautulli.entrypoints=websecure
      - traefik.http.routers.tautulli.tls.certresolver=letsencrypt
      - traefik.http.routers.tautulli.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.tautulli.middlewares=authentik@file
      - traefik.http.services.tautulli.loadbalancer.server.port=8181


  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    networks:
      - web
    cap_add:
      - NET_ADMIN
    volumes:
      - transmission:/config
      - /mnt/downloads/transmission:/downloads/transmission
    env_file:
      - ../../../global.env
      - ./env/transmission.env
    ports:
      - 51820:51820
    logging:
      driver: json-file
      options:
        max-size: 11m
    restart: unless-stopped    
    healthcheck:
        disable: true
    labels:
      - flame.type=application
      - flame.category=Pirate’s Tavern
      - flame.order=5
      - flame.name=Transmission
      - flame.url=https://transmission.${DOMAIN}
      - flame.icon=cloud-download-outline
      - traefik.docker.network=web
      - traefik.enable=true
      - traefik.http.routers.transmission-api.rule=Host(`transmission.${DOMAIN}`) && PathPrefix(`/transmission/rpc`)
      - traefik.http.routers.transmission-api.entrypoints=websecure
      - traefik.http.routers.transmission-api.priority=100
      - traefik.http.routers.transmission-api.tls=true
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN}`)
      - traefik.http.routers.transmission.entrypoints=websecure
      - traefik.http.routers.transmission.tls.certresolver=letsencrypt
      - traefik.http.routers.transmission.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.transmission.middlewares=authentik@file
      - traefik.http.services.transmission.loadbalancer.server.port=9091

networks:
  dirty-water:
    external: true
  web:
    external: true
  macvlan:
    external: true
  backend:
    external: true

volumes:
  bazarr:
    external: true
  decluttarr:
    external: true
  huntarr:
    external: true
  kometa:
    external: true
  lidarr:
    external: true
  seerr:
    external: true
  plex:
    external: true
  plexautolanguages:
    external: true
  posterizarr:
    external: true
  profilarr:
    external: true
  prowlarr:
    external: true
  radarr:
    external: true
  sabnzbd:
    external: true
  sonarr:
    external: true
  tautulli:
    external: true
  transmission:
    external: true