# Because therapy is expensive but replaying childhood games in an emulator is basically free.
name: childhood-recovery

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    env_file:
      - ../../../global.env
      - ./env/romm.env
    volumes:
      - type: volume
        source: romm
        target: /romm/assets
        volume:
          subpath: assets
      - type: volume
        source: romm
        target: /romm/config
        volume:
          subpath: config
      - type: volume
        source: romm
        target: /romm/library
        volume:
          subpath: library
      - type: volume
        source: romm
        target: /romm/resources
        volume:
          subpath: resources
    networks:
      - backend
      - cache
      - web
    labels:
      - flame.type=application
      - flame.name=ROMM
      - flame.url=https://romm.${DOMAIN}
      - flame.icon=gamepad-variant-outline
      - traefik.enable=true
      - traefik.http.routers.romm.rule=Host(`romm.${DOMAIN}`)
      - traefik.http.routers.romm.entrypoints=websecure
      - traefik.http.routers.romm.tls.certresolver=letsencrypt
      - traefik.http.routers.romm.priority=${TRAEFIK_PRIORITY}
      - traefik.http.routers.romm.middlewares=crowdsec@file,geoblock@file
      - traefik.http.services.romm.loadbalancer.server.port=8080

networks:
  backend:
    external: true
  cache:
    external: true
  web:
    external: true

volumes:
  romm:
    external: true